services:
  db:
    image: postgres:17.2
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - cloud_network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - cloud_network

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address :9090
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_volume:/data
    networks:
      - cloud_network

  frontend:
    image: s1iva/cloud-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cloud_network

  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - minio
    networks:
      - cloud_network

volumes:
  postgres_volume:
  minio_volume:

networks:
  cloud_network: